### ISSUE TITLE
description field Line Breaks as "\r" VS "\n" 

### ISSUE THREAD

**Issue by bvasoff** [taers232c/GAMADV-XTD#17]
Hi Ross,

First, thanks as always for your amazing work on GAMADV-XTD! 

I’m wondering if you can help me shed some light on an issue I’m having. I am trying to retrieve some metadata, specifically the full contents of the “description” field for a large number of clips. 

Before I started uploading with GAMADV-XTD, I was using gdcmdtools. For most, but seemingly not all of the content uploaded with gdcmdtools, when I retrieve the description metadata from google drive with a simple “show fileinfo” I only get the last line of the description field. Is it possible either google or gdcmdtools was applying line breaks differently and causing GAMADV-XTD to ignore all but the last line of text in the description field? 

If I edit (just click and save changes - not changing any text) and save the description in the google drive GUI, I get the full contents of the description field.

Also (and I suspect this is the heart of the problem), If I use googles own API tester, I get all lines of text from the description field. The line breaks are denoted with \r. After editing the text field with the GUI, the line breaks are re-written as \n

Any thoughts? I’ve been struggling with this for a while but I can’t get GAMADV-XTD to parse all of the lines with breaks denoted as \r

Any help you can offer would be hugely appreciated!

Thanks in advance,

Brian

**Comment by taers232c** [comment]
Brian,

Can you connect to me with Google Hangouts?

Ross

**Comment by taers232c** [comment]
Brian,

I'm investigating, I'll get back to you.

Ross

**Comment by taers232c** [comment]
Brian,

Google changed something. If a file had a description ABC<NL>DEF<NL> the API returned 8 characters : A B C \n D E F \n where \n is the single character newline.
Now it returns 10 characters: A B C \ n D E F \ n

For your file do: gam user user@domain.com <mailto:user@domain.com> show fileinfo <FileID> title description

Send me the output

Ross
--
ross.scroggs@gmail.com

**Comment by bvasoff** [comment]
Thanks for the fix!!
Brian

**Comment by taers232c** [comment]
Brian,

The double escaping on input is fixed in 4.57.19.

Send me a diff of the changes you made on create drivefile and I'll incorporate them.

Ross

**Comment by bvasoff** [comment]
I'm not sure my mod would have much of a "mass market" appeal, I need to have GAM output the returned google file ID in a specific format that looks like:

@U8=FILEID

The "@U8" being the code of a field I need to populate in my database, and for my purpose, I cannot have any other lines of text in stdout, or the process will not parse the line I need properly.

To achieve this, I comment out the line:

entityModifierNewValueActionPerformed([Ent.USER, user, Ent.DRIVE_FILE, titleInfo], Act.MODIFIER_WITH_CONTENT_FROM, parameters[DFA_LOCALFILENAME], i, count)

and just replace with:

print "@U8=%s" % (result[u'id'])

Unless there was a new run time switch to allow custom output syntax that would allow users to specify the text that proceeds the file ID response, so maybe: 

gam <UserTypeEntity> create|add drivefile [drivefilename <DriveFileName>] customstdout "@U8=$fileid"

Or something to that effect...  But might be more trouble than it is worth? I'll let you decide!
