### ISSUE TITLE
 gam <UserTypeEntity> deprovision fails

### ISSUE THREAD

**Issue by bengross** [taers232c/GAMADV-XTD#20]
It appears there may also be a bug with gam <UserTypeEntity> deprovision.

Users Deprovision  taers232c/GAMADV-XTD Wiki
https://github.com/taers232c/GAMADV-XTD/wiki/Users-Deprovision

This example used to work: (assuming a valid email)

$ gam user user@example.com deprovision
Getting Application Specific Password IDs for user@example.com
User: user@example.com, Deprovision 0 Application Specific Password IDs
Getting Backup Verification Codes for user@example.com
User: user@example.com, Deprovision 10 Backup Verification Codes

ERROR: 400: invalidInput - Invalid Input

**Comment by taers232c** [comment]
Ben,

Fixed 4.61.07

Give me a Hangout call.

Ross
