### ISSUE TITLE
copy drivefile - 403 Error

### ISSUE THREAD

**Issue by EveGeek** [taers232c/GAMADV-XTD#21]
gam user <user> copy drivefile id <folderid> parentid <destinationid> recursive

Getting Error:
"ERROR: 403: fieldNotWritable - The resource body includes fields which are not directly writable."

**Comment by taers232c** [comment]
Can you give me the actual command? Substitute user@domain.com <mailto:user@domain.com> for the actual user, substitute 1234 for any actual ids.

Thanks,

Ross
--
ross.scroggs@gmail.com

**Comment by EveGeek** [comment]
gam user googleadmin@evereve.com copy drivefile id 1B0A3QdE4QGUiNYQ3LUDI3m2sQpWBi-uo parentid 13hI5DmctCjn_JLQ2QFIHyvcbB-Am3Q2j recursive

**Comment by taers232c** [comment]
Thanks,

I can duplicate the problem. I'll let you know when it's fixed.

Ross
--
ross.scroggs@gmail.com

**Comment by EveGeek** [comment]
Excellent, thanks!

-Blake

**Comment by EveGeek** [comment]
Awesome! Much appreciated. Thanks again for all of your hard work.
