### ISSUE TITLE
Request: add test mode for group sync

### ISSUE THREAD

**Issue by bkgray** [taers232c/GAMADV-XTD#22]
Please consider adding a "test only" mode to the group sync command.  If included in the runstring, **testonly** would cause GAM to print details of what it would do (which members, managers, or owners would be added and/or removed).

gam update group nth-grade-students@foo. sync MANAGER  group employees@foo.com  **testonly**
   Group: nth-grade-students@sstx.org, Manager: NewGuy@foo.com  **would be added**
   Group: nth-grade-students@sstx.org, Manager: HasBeenGuy@foo.com  **would be removed**

This command will help me test for problems with my list management before I inflict the errors on users.

**Comment by taers232c** [comment]
Brian,

Will do.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Brian,

How about this?

$ gam update group testgroup sync member preview users testuser2,testuser5
Getting all Members for testgroup@rdschool.org, may take some time on a large Group...
Got 3 Members for testgroup@rdschool.org...
Group: testgroup@rdschool.org, Remove (Preview) 1 Member
  Group: testgroup@rdschool.org, Member: testuser3@rdschool.org, Removed (Preview)
Group: testgroup@rdschool.org, Add (Preview) 2 Members
  Group: testgroup@rdschool.org, Member: testuser2@rdschool.org, Added (Preview) (1/2)
  Group: testgroup@rdschool.org, Member: testuser5@rdschool.org, Added (Preview) (2/2)

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Brian,

Done. 4.61.12

Ross

**Comment by bkgray** [comment]
Thanks!!!  I owe you (yet another) beverage...
