### ISSUE TITLE
Can't authorize GAMADV - Receive ERR_EMPTY_RESPONSE error

### ISSUE THREAD

**Issue by lmcadams2** [taers232c/GAMADV-XTD#24]
I've successfully used GAMADV in the past on Cloud Shell. I tried to create a clean install on another cloud instance, and I can't authorize the permissions.  I receive a 

> This page isn’t working localhost didn’t send any data. ERR_EMPTY_RESPONSE message.   

I tried it last week a couple of times, I've cleared cache, tried a different computer and browser with the same results.  I'm not sure what to try next.

TIA for any assistance

**Comment by taers232c** [comment]
What command are you executing? Did you move your .gam folder from the old instance to the new instance?

Ross
--
ross.scroggs@gmail.com

**Comment by lmcadams2** [comment]
I am executing ./gam oauth create and I copy the website link in to my browser, click allow and then I receive the error message.

I was having the same problem in the old instance where I had the gam folder and the GAMADV folders.

**Comment by taers232c** [comment]
Copy into what browser? A browser in the cloud shell or a browser on another PC.
If it's another PC, then do
gam config no_browser true save
gam oauth create

Ross

--
ross.scroggs@gmail.com

**Comment by lmcadams2** [comment]
That was it!  Once I ran the gam config no_browser command, I was able to complete the authorization.  

Thank you so much for your prompt replies!
