### ISSUE TITLE
gam user username show vacation

### ISSUE THREAD

**Issue by Megachip** [taers232c/GAMADV-XTD#28]
`User: username, Service not applicable/Does not exist`

Happens after upgrading from 4.65.02 to 4.65.21

**Comment by taers232c** [comment]
Do the following
gam update project
gam user user@domain.com <mailto:user@domain.com> check serviceaccount

Ross
--
ross.scroggs@gmail.com

**Comment by EveGeek** [comment]
@Megachip, I was getting similar errors for other misc commands. Running the 'check serviceaccount' command revealed that APIs had changed and I needed to re-authorize the app. This should solve it for your.

Thanks again, @taers232c
