### ISSUE TITLE
Problem with calendar event responseStatus

### ISSUE THREAD

**Issue by bkgray** [taers232c/GAMADV-XTD#32]
Using GAMADV-XTD 4.65.56, "Calendar show events" and "calendar print events" report errors when attendees.responseStatus is included as a field to report.

These commands work as expected:

- gam calendar eventOwner@sstx.org print events matchfield summary "^Sample Event" fields summary,attendees
- gam calendar eventOwner@sstx.org print events matchfield summary "^Sample Event" fields summary,attendees.displayname

but this command fails:

gam calendar eventOwner@sstx.org print events starttime 2019-02-11 endtime 2019-02-13 matchfield summary "^Sample Event" fields attendees.responsestatus

Output is: 

Command: gam calendar eventOwner@sstx.org print events starttime 2019-02-11 endtime 2019-02-13 matchfield summary "^Sample Event" fields >>>attendees.responseStatus<<<

ERROR: Invalid argument: Expected <additionalguests|comment|displayname|email|id|optional|organizer|resource|responseStatus|self>

Am I mis-using responseStatus?

**Comment by taers232c** [comment]
It's a bug. I'm on jury duty, I'll try to post a fix before I go in this morning, otherwise it'll be this evening.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Briam,

Try 4.65.57

Ross
--
ross.scroggs@gmail.com

**Comment by bkgray** [comment]
Thanks.  It works as expected now.
