### ISSUE TITLE
ReplyToCustom sends wrong error

### ISSUE THREAD

**Issue by daallgeier** [taers232c/GAMADV-XTD#38]
When running the `replyToCustom` flag on a group and forgetting the `customReplyTo <EmailAddress>` flag I get the following error message:

`Not Updated: replyto REPLY_TO_CUSTOM requires *cumtomReplyTo* <EmailAddress>`

`cumtom` is obviously misspelled in the error message.

**Comment by taers232c** [comment]
I will correct, thank you.

Ross
--
ross.scroggs@gmail.com
