### ISSUE TITLE
Duplicate file extension

### ISSUE THREAD

**Issue by pmorriss** [taers232c/GAMADV-XTD#6]
I am using get drivefile (with the target folder option) to download team drive files. A number have a repeated extension, e.g. IMG_0017.JPGJPG. There are a number of files in the same team drive that don't have this and the difference is that they have lowercase extensions. So it looks like the uppercase extension is somehow causing it to be repeated.

**Comment by taers232c** [comment]
Paul,

I'll fix this, thanks for pointing it out.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Paul,

Should be fixed.

Ross

**Comment by pmorriss** [comment]
I can confirm that it is in the latest release.
